export const SUPPLIER_TEXT_CONFIG = {
    SUPPLIER_PAGE_HEADER: 'Danh sách nhà cung cấp',
    SUPPLIER_MODAL_PAGE_HEADER: 'Thông tin nhà cung cấp',
    SUPPLIER_SEARCH_PLACEHOLDER: 'Nhập từ khóa tìm kiếm',
    SUPPLIER_GROUP_RADIO: 'Tổ chức',
    SUPPLIER_INDIVIDUAL_RADIO: 'Cá nhân',
    SUPPLIER_COSTOMER_CHECKBOX: 'Là khách hàng',
    SUPPLIER_ACTION_ALL_BTN: 'Thực hiện hàng loạt',
    SUPPLIER_UTILITIES_BTN: 'Tiện ích',
    SUPPLIER_FILTER_BTN: 'Lọc',
    SUPPLIER_ADD_BTN: 'Thêm',
    SUPPLIER_SAVE_BTN: 'Cất',
    SUPPLIER_DELETE_BTN: 'Xóa',
    SUPPLIER_SAVE_ADN_ADD_BTN: 'Cất và thêm',
    SUPPLIER_CANCEL_BTN: 'Hủy',

    SUPPLIER_CODE_FIELD_LBL: 'Mã nhà cung cấp',
    SUPPLIER_NAME_FIELD_LBL: 'Tên nhà cung cấp',
    SUPPLIER_TAXCODE_FIELD_LBL: 'Mã số thuế',
    SUPPLIER_PHONE_FIELD_LBL: 'Điện thoại',
    SUPPLIER_WEBSITE_FIELD_LBL: 'Website',
    SUPPLIER_GROUP_FIELD_LBL: 'Nhóm nhà cung cấp',
    SUPPLIER_ADDRESS_FIELD_LBL: 'Địa chỉ',
    SUPPLIER_EMPLOYEE_FIELD_LBL: 'Nhân viên mua hàng',
    SUPPLIER_PAYMENT_TERM_FIELD_LBL: 'Điều khoản thanh toán',
    SUPPLIER_NUM_DAY_OWED_FIELD_LBL: 'Số ngày được nợ',
    SUPPLIER_MAX_DEBT_FIELD_LBL: 'Số nợ tối đa',
    SUPPLIER_ACCOUNT_PAYABLE_FIELD_LBL: 'Tài khoản công nợ phải trả',
    SUPPLIER_CONTACT_NAME_FIELD_LBL: 'Người liên hệ',
    SUPPLIER_REPRESENTATIVE_FIELD_LBL: 'Đại diện theo PL',
    SUPPLIER_REPRESENTATIVE_NAME_FIELD_LBL: 'Họ và tên',
    SUPPLIER_VOCATIVE_FIELD_LBL: 'Xưng hô',
    SUPPLIER_EMAIL_FIELD_LBL: 'Email',
}