export const RECEIPT_PAYMENT_TEXT_CONFIG = {
    RECEIPT_PAYMENT_PAGE_HEADER: "Thu chi tiền mặt",
    RECEIPT_PAYMENT_MODAL_PAGE_HEADER: "Thông tin nhà cung cấp",
    RECEIPT_PAYMENT_SEARCH_PLACEHOLDER: "Nhập từ khóa tìm kiếm",
    RECEIPT_PAYMENT_ACTION_ALL_BTN: "Thực hiện hàng loạt",
    RECEIPT_PAYMENT_UTILITIES_BTN: "Tiện ích",
    RECEIPT_PAYMENT_FILTER_BTN: "Lọc",
    RECEIPT_PAYMENT_ADD_RECEIPT_BTN: "Thêm thu tiền",
    RECEIPT_PAYMENT_ADD_PAYMENT_BTN: "Thêm chi tiền",
    RECEIPT_PAYMENT_SAVE_BTN: "Cất",
    RECEIPT_PAYMENT_DELETE_BTN: "Xóa",
    RECEIPT_PAYMENT_SAVE_AND_ADD_BTN: "Cất và thêm",
    RECEIPT_PAYMENT_CANCEL_BTN: "Hủy",
};
