export const RECEIPT_PAYMENT_TEXT_CONFIG = {
    RECEIPT_PAYMENT_PAGE_HEADER: "Thu chi tiền mặt",
    RECEIPT_PAYMENT_MODAL_PAGE_HEADER: "Thông tin nhà cung cấp",
    RECEIPT_PAYMENT_SEARCH_PLACEHOLDER: "Nhập từ khóa tìm kiếm",
    RECEIPT_PAYMENT_ACTION_ALL_BTN: "Thực hiện hàng loạt",
    RECEIPT_PAYMENT_UTILITIES_BTN: "Tiện ích",
    RECEIPT_PAYMENT_FILTER_BTN: "Lọc",
    RECEIPT_PAYMENT_ADD_RECEIPT_BTN: "Thêm thu tiền",
    RECEIPT_PAYMENT_ADD_PAYMENT_BTN: "Thêm chi tiền",
    RECEIPT_PAYMENT_SAVE_BTN: "Cất",
    RECEIPT_PAYMENT_EDIT_BTN: "Sửa",
    RECEIPT_PAYMENT_RECORD_BOOK_BTN: "Ghi sổ",
    RECEIPT_PAYMENT_DELETE_BTN: "Xóa",
    RECEIPT_PAYMENT_SAVE_AND_ADD_BTN: "Cất và thêm",
    RECEIPT_PAYMENT_CANCEL_BTN: "Hủy",

    /* FORM */
    ACCOUNT_OBJECT_CODE_FIELD: "Mã đối tượng",
    ACCOUNT_OBJECT_NAME_FIELD: "Tên đối tượng",
    ACCOUNT_OBJECT_CONTACT_NAME_FIELD: "Người nhận",
    ADDRESS_FIELD: "Địa chỉ",
    EMPLOYEE_FIELD: "Nhân viên",
    RECEIPT_REASON_FIELD: "Lý do nộp",
    PAYMENT_REASON_FIELD: "Lý do chi",
    ADDING_FIELD: "Số lượng",
    ACCOUNTING_DATE_FIELD: "Ngày hạch toán",
    RECEIPT_DATE_FIELD: "Ngày phiếu thu",
    RECEIPT_NUMBER_FIELD: "Số phiếu thu",
    PAYMENT_DATE_FIELD: "Ngày phiếu chi",
    PAYMENT_NUMBER_FIELD: "Số phiếu chi",
};
